# Use an official Nvidia CUDA runtime as a parent image
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

# Avoid interactive prompts - auto-select defaults for any prompts 
ARG DEBIAN_FRONTEND=noninteractive

# Set timezone for tzdata package as it's a dependency for some packages
ENV TZ=America/Los_Angeles

# Set the working directory in the container
WORKDIR /app

# Install build dependencies: build-essential includes GCC, G++, and make and is already part of the DEVEL development image; libffi-dev for Foreign Function Interface (FFI); libssl-dev for SSL support
RUN apt-get update && apt-get install -y \
	software-properties-common \
	libffi-dev \
	libssl-dev \
	poppler-utils \
	libreoffice \
	git \
	net-tools \
	iproute2

# Copy the current directory contents into the container at /app
COPY . /app

# OPTIONAL - Change fPIC level, and Set CUDA optimizations as per your GPU arch - `arch=compute_86,code=sm_86` is for RTX 3000 Ampere, `arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90` is for Ampere & Hopper etc
# ENV CUDA_NVCC_FLAGS="-Xcompiler -fPIC -O3 --use_fast_math -gencode arch=compute_86,code=sm_86"

# Clone specific llama.cpp release
# RUN git clone https://github.com/ggerganov/llama.cpp.git

# Build llama.cpp
# WORKDIR /app/llama.cpp
# RUN make GGML_CUDA=1 -j $(nproc)

# Add the build path to the system PATH
# ENV PATH "/app/llama.cpp:${PATH}"

# Change back to the main app directory
# WORKDIR /app

# Add deadsnakes PPA for Python 3.11 - since the Ubuntu rep may not contain our desired version of Python, we install a popular Personal Package Archive (PPA), deadsnakes, to get the desired version which will pull the latest 3.11.X (other specific subversions are not hosted)
RUN add-apt-repository ppa:deadsnakes/ppa -y

# Install Python 3.11 and upgrade pip, while ensuring pip is installed
RUN apt-get update && apt-get install -y python3.11 python3.11-venv python3.11-dev && python3.11 -m ensurepip

# Create a virtual environment to ensure Python Packages are isolated from the system
RUN python3.11 -m venv /venv

# Activate the venv (modifying PATH is typical for a container env rather than 'activate')
ENV PATH="/venv/bin:$PATH"

# Now upgrade pip from within the venv
RUN pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements_linux.txt

# Install PyTorch Nightly Build for CUDA 12.4 and dependencies for Flash Attention 2
RUN pip install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cu124 && \
	pip install -v wheel==0.37.1 ninja==1.11.1 packaging==24.1

# Install Flash Attention 2 from the Pre-Built Wheel
# RUN pip install -v prebuilt_wheels/flash_attn-2.6.3-cp310-cp310-linux_x86_64.whl --no-build-isolation

# make port 5000 available to the world outside this container
EXPOSE 5000
EXPOSE 8080
EXPOSE 9069

# Set the working directory in the container
WORKDIR /app/web_app

# Run application
CMD ["python3", "app.py"]