# BUILD WITH: docker build --no-cache --progress=plain -t lars-v333 .
# RUN WITH: docker run --gpus all -p 5000:5000 -p 9069:9069 -p 8080:8080 -v lars_storage:/app/lars_storage lars-v333
# STORAGE VOLUME: docker volume create lars_storage

# Use an official Nvidia CUDA runtime as a parent image
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

# Avoid interactive prompts - auto-select defaults for any prompts 
ARG DEBIAN_FRONTEND=noninteractive

# Set timezone for tzdata package as it's a dependency for some packages
ENV TZ=America/Los_Angeles

# Set the working directory in the container
WORKDIR /app

# Install Python, PIP, and other dependencies
RUN apt-get update && apt-get install -y python3.10 python3-pip git libreoffice poppler-utils

# Copy the current directory contents into the container at /app
COPY . /app

# OPTIONAL - Change fPIC level, and Set CUDA optimizations as per your GPU arch - `arch=compute_86,code=sm_86` is for RTX 3000 Ampere, `arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90` is for Ampere & Hopper etc
# ENV CUDA_NVCC_FLAGS="-Xcompiler -fPIC -O3 --use_fast_math -gencode arch=compute_86,code=sm_86"
ENV CUDA_NVCC_FLAGS="-gencode arch=compute_80,code=sm_80"

# Clone specific llama.cpp release
RUN git clone -b b4174 https://github.com/ggerganov/llama.cpp.git

# Build llama.cpp
WORKDIR /app/llama.cpp
RUN make GGML_CUDA=1 -j $(nproc)

# Add the build path to the system PATH
ENV PATH="/app/llama.cpp:${PATH}"

# Change back to the main app directory
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements_linux.txt

# Install PyTorch Nightly Build for CUDA 12.4 and dependencies for Flash Attention 2
RUN pip install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cu124 && \
	pip install -v wheel==0.37.1 ninja==1.11.1 packaging==24.1

# Install Flash Attention 2 from the Pre-Built Wheel
RUN pip install -v prebuilt_wheels/flash_attn-2.6.3-cp310-cp310-linux_x86_64.whl --no-build-isolation

# make port 5000 available to the world outside this container
EXPOSE 5000
EXPOSE 6003
EXPOSE 8080
EXPOSE 9069

# Set the working directory in the container
WORKDIR /app/web_app

# Run application
CMD ["python3", "app.py"]